### PR TITLE
Start of APD Testing

### PR DESCRIPTION
**Pull request by cobracmder**
Start of APD Testing using python and nose.

### CODE REVIEW

**Comment by cbrune** [comment]
The code looks OK to me.

I would beef up the commit message a bit.  You could reuse some of the text from README.md in the commit message.

**Comment by cobracmder** [comment]
@cbrune done.

**Comment by byford** [comment]
Hi Carlos,

Good start.  I'm not a huge fan of naming the test files by number, it seems like it'll be hard to remember.  What do you think about organizing the tests as a single file by subsystem?

For example:

acpi.py
sensors.py
switch_asic.py
etc...

Otherwise, looks great.  Ship it.

**Comment by cobracmder** [comment]
@byford done.

**Comment by cobracmder** [comment]
pushed to master

**Pull request closed without merging**
